apiVersion: v1
kind: Pod
metadata:
  name: practice_pod
spec:
  containers:
    - name: practice-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      
